---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: grafana-influxdb-yml,grafana-overview-json,grafana-overview-yml
  labels:
    app: marax
  name: marax
  namespace: marax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marax
  template:
    metadata:
      labels:
        app: marax
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: influxdb
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: influxdb
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: marax
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: default
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: ingenue-teasel-willful-addendum
          image: influxdb:1.8
          name: influxdb
          ports:
            - containerPort: 8086
          resources:
            limits:
              cpu: 900m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: influxdb-init
              readOnly: true
        - env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: grafana
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: grafana
          image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-influxdb-yml
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-overview-yml
            - mountPath: /var/lib/grafana/dashboards
              name: grafana-overview-json
      volumes:
        - configMap:
            name: influxdb
          name: influxdb-init
        - configMap:
            name: grafana-influxdb-yml
          name: grafana-influxdb-yml
        - configMap:
            name: grafana-overview-yml
          name: grafana-overview-yml
        - configMap:
            name: grafana-overview-json
          name: grafana-overview-json