---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "grafana-influxdb-yml,grafana-overview-json,grafana-overview-yml"
  name: marax
  namespace: marax
  labels:
    app: marax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marax
  template:
    metadata:
      labels:
        app: marax
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.8
          env:
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: username
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: password
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: marax
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: default
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: ingenue-teasel-willful-addendum
          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "900m"
          volumeMounts:
            - name: influxdb-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
        - name: grafana
          image: grafana/grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana
                  key: password
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "900m"
          volumeMounts:
            - name: grafana-influxdb-yml
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-overview-yml
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-overview-json
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: influxdb-init
          configMap:
            name: influxdb
        - name: grafana-influxdb-yml
          configMap:
            name: grafana-influxdb-yml
        - name: grafana-overview-yml
          configMap:
            name: grafana-overview-yml
        - name: grafana-overview-json
          configMap:
            name: grafana-overview-json
