apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  name: grafana
  namespace: marax
spec:
  encryptedData:
    password: AgAviX/35vj2zjvLfiRqLhxPw6QElxFJH5VKxfdSrPcXsUtKGYpMsHi8YxqrR+Cr5Vxi17NblFVuUThvO6kMze5z9+UiKpakdcwTDYuVu+u3SgE2APXIQk7xGkRCBwsivTyBwWU8ZBBvM9gD8NuESPEFUpmSgOxlGwQ1+YOiknRcwSmnHeZVCfxT6igDuDdSxIw93oA2EdA11kYd7DEFWca9VWir851DIa+e/+ZlNBOqv0MI4lUKnXM5tP8bEC6vRL9UFA9xlVvTYdFKzVv+oiu3Im2r6fjMJADRwRlUKWtHohYL0rymruCJh1Nq9CTmYNkB6aCNOLCQKJbQ/XwnmxpjDUNwHj+bhXf+XriE9Y/F689LJ9fbSeVagSmekJzpW6HQ3IfA/I9MCNNXMgzP7QjcibE+PvU1bcXXkFmpE8DqcRrrfKDGVlJPWy/FZpIr3Rh95tG0REWE7BJj3nrPl24X1zzv70PVt5pWUYS2FBDasTBi/89CzcDO28LVyVFN4i7NJRYeL8GzlKM25lsMviejkq198qwAmDgY9BjeuHDQ/AxKu0k5VjW7y8IhADJlVl6TJny7BQJPLCGlxvwbP51S0hKrdqINmxeaJXFDQNEkXotPSMZl3yg6y76hWpJcgHUQo8jTjkPaVt0HmexN8yIeFfJyscZwm3OSMN/tcL6DZBZITam22N5aAP50j6+zBTqcRqGKQLUCEscA6TPxKAg9M4R5fw==
    username: AgBtrlX5m904zAXgBf387vTBoylCBQGZckzBrqOXfJ+4ndhkccg0mSA3FODl9qWysV5LtF2MbtWnLgPElAu/y6tUxzrCrUjL3t6xp817ZjvNUqZrvLT7FS6hGviYuOPi9fcUHNfXvtBRHcdco+roocMNDYNVYOob/I6lLaOvaXE9UlL1k3CkpEeIGmwl74FxRwPFve25KsBAZxnaxqT0I+1LD3+aNdjUUTIE1+LYUqzXkmv6qYaD3IAfagtKgayAlGMtumKCwGv6jso56ZPDxGTp75tsB84/rWrbqh/zQtZR/SPyx1Cg8gJuOqPRER5PDkeJf1hS06o3ixJC3bKXmwfxeA54E0NFongIZuaSMU0YnV2yF0GMqJcXiPdO5AakBvaFKNArkr1+YyyEUea5YmHWbWHEFSATysFjUUlU/hM4o6XqlbzqhZhqJZaVOUqua3QAzvXRtamsBRftw35TvPUIvbHfzeGKHMqZQCqKDlsOG946LDsRhBunQnEYFkeUKDZBcCKbJcVG16kTUQ0sn+Fieykw/bKVzY/jn5IzBLxAK+T9kD2dJO4pqbrpgxraJp8ekVLnswvwVgq45OEWp+hOmx/ffVXmC53KKKsuo6ffrLxuV9n7Nr7Xuu9kt0vL8fWlhpA+zyK0QL2qrOVFgdXdRHTYt4e70OxWNIgvcXbd2qfr8Y/BGNFxEXlM79ws3HqjGNuH3w==
  template:
    metadata:
      name: grafana
      namespace: marax
    type: Opaque
