apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  name: influxdb
  namespace: marax
spec:
  encryptedData:
    password: AgClfM/Q4FBrM7jfduvSYnHHg+Gw4vrPOVsRvialsjPgbfVBd68oV0m8dGDsdsTl5Ia2JlhU0FbZXwetCCqtyw16l8X5tY5jBrdInqN2sk6cDJsJ+0T0bmZN7jYbrs4WD5IpF7FEdcoMKBkx+raA1nMiYAd2coq3p7FStcYkglDOSAYlUDnEz1qTur5xGDvePb9Svid6XwsJY0hUl9p50Cm5GqUyk2/YhNUxwKwg9B7Sj2yAsDtn57tRWIcNW27GstQxXF4S56q571+yJ5ycgKKR4BweeJyjRhd3Ghzt5V9o4ua9hviINHF2BXOxD/UX+/lZpKzktNU8SWjP5TTfayuWF9mb4oOLeTs/vbwg2VAzSkLD2MHVe2tfIQowh63LJ0ODni0UZ7U9LD6QOkNvt6h4y2afRgayK7638EA57b8UPMOwijTuCS0cj6tTzTyXsX8AsFuVCYRY4W8J3Rd4J3DWuUMGgJ5ReWBqTU5c/3XdJVuQNANxBOrLxFH4r7iSmDxS/GtZeA+6UxtMh1D6pMSWbvaDTCQe8ec3ihUpI4EdTKlo7DOtjaX145OtipNuEKUNDnkNtDWw3PJqESUPfCN2ZaVL7auBbird++ssmuBgF+HttV5t+4xm0ObTLq8CoczUCfH424iewYE4Vg/fBNwz64wlBotN84zBQn625gX31vpUoYcQp5cCZQqOgFmMjC+/gTtRf8zwrw==
    username: AgC5zBh/XJMC7BPlWhbrTpRPEbu6C09E6QTDIaUCQPTh+lw7wImkX4AoLCeqfn/nWLaz2YJ+oik78cx2m9BPNN/oOWIoggEXLF1vImqYqrNwT6XYqrcFffMwKqBLSFpo3TbHsq7C5RerFr1dVbKPFLtN0RoMNXl+RO6aJhELX411/y8fos+9twsTC4uQJnf+AwhPkKhqHZ42jzvStzThG04bf9ugNSVp75StUA+gEI0WWhXTVxEf9H2EsXI32/Mm9wBWGHq+rdo89ZAgYfVP5SDZrTEfrCeTXfLMWyaMLaCzCx7JIsvkx2iQvWBk+EGEZ9KdrPDEwp8KWmU8LzkynPoucuFVchRs01ZYAgGQbl//RbfcEXgvfh8yh3Es8KJW/Niy3v+EA6R/MHoFuIPl4SZRe731nTgD28mHu0ofeTM1RYsMA82F9BYu0L+wAQbo5VFn7ks8uWjOyLFd+fIGFDYxjjsWa1lk0CCzjnzIXiwsbntwBmUrxPlV9VOV1ZHK2aQQzmwxpOQEp7pyqkkRDyqW8f87qVIfR8JR2kET62IiMIigcSXj6JBKgscHeB4PMzbhTuF6W+grL7guEkYpqU1J6GiN6qN566vMMpWB4ThJJ2CG2qIJXUHUPCkjKMqD3gij0ZXfSwXxfQA21lKGZw5drRE8ZE/JjDewz6xExjOJqOzKvt4rsWAcxXdGnIAT+n5d+xkUKg==
  template:
    metadata:
      name: influxdb
      namespace: marax
    type: Opaque
