---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marax
  name: grafana
  namespace: marax
spec:
  ports:
    - name: grafana
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: marax
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marax
  name: influxdb
  namespace: marax
spec:
  ports:
    - name: influxdb
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: marax
  type: LoadBalancer
