---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: marax-monitoring
  name: grafana
  namespace: marax-monitoring
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32597
    port: 80
    targetPort: 3000
  selector:
    app: marax-monitoring
  type: LoadBalancer
