FROM alpine

COPY ./serial_to_file.sh /usr/local/bin/serial_to_file
RUN chmod +x /usr/local/bin/serial_to_file

RUN mkdir /var/log/marax

CMD ["/bin/sh", "-c", "cat /dev/ttyUSB0 | serial_to_file | tee -a /var/log/marax/temp.log"]
