FROM alpine

COPY ./serial_to_file.sh /usr/local/bin/serial_to_file
RUN chmod +x /usr/local/bin/serial_to_file

RUN mkdir /var/log/marax

CMD ["serial_to_file", "/dev/ttyUSB0", "/var/log/marax/temp.log"]
